# Generated by Django 5.0.14 on 2026-06-27 12:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GanTokenBaiThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_to', models.PositiveIntegerField(default=1)),
                ('trang_thai', models.CharField(choices=[('da_gan', 'Đã gán'), ('da_thu', 'Đã thu'), ('huy', 'Hủy')], default='da_gan', max_length=50)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ly_do_huy', models.TextField(blank=True, null=True)),
                ('thoi_gian_gan', models.DateTimeField(default=django.utils.timezone.now)),
                ('thoi_gian_thu', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_huy', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gán QR bài thi',
                'verbose_name_plural': 'Gán QR bài thi',
                'db_table': 'gan_token_bai_thi',
            },
        ),
        migrations.CreateModel(
            name='HocVien',
            fields=[
                ('ma_hoc_vien', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('so_bao_danh', models.IntegerField(blank=True, null=True)),
                ('ho_ten', models.CharField(max_length=255)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('gioi_tinh', models.CharField(blank=True, max_length=20, null=True)),
                ('trang_thai', models.CharField(default='dang_hoc', max_length=50)),
            ],
            options={
                'verbose_name': 'Học viên',
                'verbose_name_plural': 'Học viên',
                'db_table': 'hoc_vien',
            },
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('ma_lop', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ten_lop', models.CharField(max_length=255)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lớp',
                'verbose_name_plural': 'Lớp',
                'db_table': 'lop',
            },
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('ma_mon', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ten_mon', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'db_table': 'mon_hoc',
            },
        ),
        migrations.CreateModel(
            name='CanBo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_can_bo', models.CharField(max_length=50, unique=True)),
                ('ten_can_bo', models.CharField(max_length=255)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('gioi_tinh', models.CharField(blank=True, max_length=20, null=True)),
                ('cap_bac', models.CharField(blank=True, max_length=100, null=True)),
                ('chuc_vu', models.CharField(blank=True, max_length=150, null=True)),
                ('don_vi', models.CharField(blank=True, max_length=255, null=True)),
                ('sdt', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('trang_thai', models.CharField(choices=[('dang_lam_viec', 'Đang làm việc'), ('nghi_cong_tac', 'Nghỉ công tác')], default='dang_lam_viec', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='can_bo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cán bộ',
                'verbose_name_plural': 'Cán bộ',
                'db_table': 'can_bo',
            },
        ),
        migrations.CreateModel(
            name='BaiThiScanDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_text', models.CharField(blank=True, max_length=120, null=True)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('diem_nhan_dien', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diem_chot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nhan_xet', models.TextField(blank=True, null=True)),
                ('trang_thai', models.CharField(default='cho_cham', max_length=50)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thoi_gian_chot', models.DateTimeField(blank=True, null=True)),
                ('nguoi_cham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_cham', to='exam_token.canbo')),
                ('gan_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_token.gantokenbaithi')),
                ('hoc_vien', models.ForeignKey(blank=True, db_column='ma_hoc_vien', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_token.hocvien')),
            ],
            options={
                'verbose_name': 'Bài thi scan điểm',
                'verbose_name_plural': 'Bài thi scan điểm',
                'db_table': 'bai_thi_scan_diem',
            },
        ),
        migrations.CreateModel(
            name='ChamDiemChiTiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cau_so', models.PositiveIntegerField()),
                ('noi_dung', models.CharField(max_length=255)),
                ('diem_toi_da', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('diem_dat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('bai_thi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='exam_token.baithiscandiem')),
            ],
            options={
                'verbose_name': 'Chấm điểm chi tiết',
                'verbose_name_plural': 'Chấm điểm chi tiết',
                'db_table': 'cham_diem_chi_tiet',
                'ordering': ['cau_so'],
            },
        ),
        migrations.AddField(
            model_name='gantokenbaithi',
            name='hoc_vien',
            field=models.ForeignKey(db_column='ma_hoc_vien', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='exam_token.hocvien'),
        ),
        migrations.AddField(
            model_name='hocvien',
            name='lop',
            field=models.ForeignKey(db_column='ma_lop', on_delete=django.db.models.deletion.PROTECT, related_name='hoc_viens', to='exam_token.lop'),
        ),
        migrations.CreateModel(
            name='PhienThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phien_thi', models.CharField(max_length=150, unique=True)),
                ('ten_ky_thi', models.CharField(default='Kiểm tra', max_length=255)),               
                ('ngay_thi', models.DateField()),
                ('phong_thi', models.CharField(max_length=100)),
                ('thoi_gian_lam_bai', models.PositiveIntegerField(choices=[(60, '60 phút'), (90, '90 phút'), (120, '120 phút'), (150, '150 phút'), (180, '180 phút')], default=90)),
                ('trang_thai', models.CharField(choices=[('dang_mo', 'Đang mở'), ('dang_lam_bai', 'Đang làm bài'), ('da_thu', 'Đã thu bài'), ('hoan_thanh', 'Hoàn thành'), ('huy', 'Hủy')], default='dang_mo', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('can_bo_coi_thi_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phien_thi_cb1', to='exam_token.canbo')),
                ('can_bo_coi_thi_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phien_thi_cb2', to='exam_token.canbo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('lop', models.ForeignKey(db_column='ma_lop', on_delete=django.db.models.deletion.PROTECT, related_name='phien_this', to='exam_token.lop')),
                ('mon', models.ForeignKey(db_column='ma_mon', on_delete=django.db.models.deletion.PROTECT, related_name='phien_this', to='exam_token.monhoc')),
            ],
            options={
                'verbose_name': 'Phiên thi',
                'verbose_name_plural': 'Phiên thi',
                'db_table': 'phien_thi',
            },
        ),
        migrations.AddField(
            model_name='gantokenbaithi',
            name='phien_thi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='exam_token.phienthi'),
        ),
        migrations.CreateModel(
            name='ExamSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('can_bo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_token.canbo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('phien_thi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='exam_token.phienthi')),
            ],
            options={
                'verbose_name': 'Log phiên thi',
                'verbose_name_plural': 'Log phiên thi',
                'db_table': 'exam_session_log',
            },
        ),
        migrations.AddField(
            model_name='baithiscandiem',
            name='phien_thi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_token.phienthi'),
        ),
        migrations.CreateModel(
            name='QRBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_dot', models.CharField(max_length=80, unique=True)),
                ('so_luong', models.PositiveIntegerField(default=0)),
                ('trang_thai', models.CharField(default='dang_su_dung', max_length=50)),
                ('printed_pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đợt in QR',
                'verbose_name_plural': 'Đợt in QR',
                'db_table': 'qr_batch',
            },
        ),
        migrations.CreateModel(
            name='QRTokenBaiThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=120, unique=True)),
                ('trang_thai', models.CharField(choices=[('chua_gan', 'Chưa gán'), ('da_gan', 'Đã gán'), ('da_thu', 'Đã thu'), ('huy', 'Hủy')], default='chua_gan', max_length=50)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='exam_token.qrbatch')),
            ],
            options={
                'verbose_name': 'QR bài thi',
                'verbose_name_plural': 'QR bài thi',
                'db_table': 'qr_token_bai_thi',
            },
        ),
        migrations.AddField(
            model_name='gantokenbaithi',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='exam_token.qrtokenbaithi'),
        ),
        migrations.AddField(
            model_name='baithiscandiem',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_token.qrtokenbaithi'),
        ),
        migrations.AddIndex(
            model_name='hocvien',
            index=models.Index(fields=['lop', 'so_bao_danh'], name='hoc_vien_ma_lop_746897_idx'),
        ),
        migrations.AddIndex(
            model_name='phienthi',
            index=models.Index(fields=['lop'], name='phien_thi_ma_lop_6fc987_idx'),
        ),
        migrations.AddIndex(
            model_name='phienthi',
            index=models.Index(fields=['trang_thai'], name='phien_thi_trang_t_d40402_idx'),
        ),
        migrations.AddIndex(
            model_name='examsessionlog',
            index=models.Index(fields=['phien_thi', 'created_at'], name='exam_sessio_phien_t_0ef548_idx'),
        ),
        migrations.AddIndex(
            model_name='examsessionlog',
            index=models.Index(fields=['action'], name='exam_sessio_action_c120a8_idx'),
        ),
        migrations.AddIndex(
            model_name='qrtokenbaithi',
            index=models.Index(fields=['trang_thai'], name='qr_token_ba_trang_t_fdd562_idx'),
        ),
        migrations.AddIndex(
            model_name='qrtokenbaithi',
            index=models.Index(fields=['batch'], name='qr_token_ba_batch_i_8ed299_idx'),
        ),
        migrations.AddIndex(
            model_name='gantokenbaithi',
            index=models.Index(fields=['phien_thi', 'hoc_vien', 'trang_thai'], name='gan_token_b_phien_t_c4e244_idx'),
        ),
        migrations.AddIndex(
            model_name='baithiscandiem',
            index=models.Index(fields=['trang_thai'], name='bai_thi_sca_trang_t_90bdb3_idx'),
        ),
        migrations.AddIndex(
            model_name='baithiscandiem',
            index=models.Index(fields=['token_text'], name='bai_thi_sca_token_t_c941a2_idx'),
        ),
    ]
